language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune
# `script` is default `npm test` which just prints a no-op message.
after_success:
  - npm run semantic-release
branches:
  only:
    - master
