version: '2'
services:

  pattern-lab:
    image: comicrelief/frost-node:latest
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    command: yarn run build
    working_dir: /usr/src/app
